name: ably_flutter
description: Flutter plugin for Ably, a realtime messaging service that powers synchronized digital experiences in realtime on Android and iOS.
version: 1.2.6
repository: https://github.com/ably/ably-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  fake_async: ^1.1.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

  # Specifying a slightly older version minimum for the 'pure' Dart test package
  # because the flutter_test package needs an older version of test_api.
  test: ^1.16.7


flutter:
  plugin:
    platforms:
      android:
        package: io.ably.flutter.plugin
        pluginClass: AblyFlutter
      ios:
        pluginClass: AblyFlutter
