on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      # This step requires fetch of test_integration packages because flutter format and 
      # flutter analyze check test_integration package too
      - name: 'Install dependencies'
        run: |
          flutter pub get
          cd test_integration
          flutter pub get
          cd ..

      - name: 'Check formatting issues in the code'
        run: flutter format --set-exit-if-changed .
        
      # Suppressing info - deprecated entries fall under info, and CI shouldn't fail if there are any Deprecated APIs
      # FIXME(ikurek): We should probably just configure linter to ignore deprecation, instead of disabling errors here
      - name: 'Statically analyze the Dart code for any errors'
        run: 'flutter analyze --no-pub --no-fatal-infos .'

      - name: 'Run unit tests'
        run: flutter test --no-pub
