on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      
      - name: Get Flutter Packages
        run: flutter pub get

      - name: Install dartdoc global package via pub tool in the Flutter context
        run: |
          flutter pub global activate dartdoc

      - name: Build Documentation
        run: |
          flutter pub global run dartdoc
          ls -al doc/api
      
      # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#using-workflow-commands-to-access-toolkit-functions
      - name: Define Deployment Constants
        id: define_deployment_constants
        run: |
          echo "::set-output name=environment::${{ github.event_name === 'pull_request' ? `staging/pull/${github.event.pull_request.number}/dartdoc` : 'main/dartdoc' }}"
          echo "::set-output name=environment_url::${{ github.event_name === 'pull_request' ? `https://sdk.ably.com/builds/ably/ably-flutter/pull/${github.event.pull_request.number}/dartdoc/` : 'https://sdk.ably.com/builds/ably/ably-flutter/main/dartdoc/' }}"

      # https://docs.github.com/en/rest/reference/repos#create-a-deployment
      # Based (very loosely) on the approach found here: https://github.com/SanderKnape/pr-deployments
      # Regarding getting the SHA for the HEAD of the branch underlying when triggered by a PR:
      # - github.sha is not helpful as it just gives us the SHA for the temporary merge commit created temporarily
      #   for this workflow run (the deployment then gets explicitly marked as "temporarily" deployed)
      # - https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow#comment107561661_59819441
      # - https://stackoverflow.com/a/61035010
      # When triggered by a push to the main branch the the SHA represents the triggering commit:
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
      - name: Create Deployment
        id: create_deployment
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments
          repository: ${{ github.repository }}
          ref: ${{ github.event_name === 'pull_request' ? github.event.pull_request.head.sha : github.sha }}
          environment: ${{ steps.define_deployment_constants.outputs.environment }}
          auto_merge: false
          required_contexts: '[]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://docs.github.com/en/rest/reference/repos#create-a-deployment-status
      # re mediaType values: https://docs.github.com/en/rest/overview/api-previews
      # because, ultimatey via: https://github.com/octokit/request.js/#request
      - name: Set Deployment Status to In Progress
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: ${{ steps.define_deployment_constants.outputs.environment }}
          environment_url: ${{ steps.define_deployment_constants.outputs.environment_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: in_progress
          mediaType: '{"previews": ["flash", "ant-man"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Default shell is bash: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
      # jq emits `null` if the `pull_request` key is not found.
      # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md#cli-tools
      # https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
      # https://docs.aws.amazon.com/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-managing-objects-sync
      # https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/sync.html
      - name: Upload to Amazon S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_S3_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          REMOTE_PATH_SUFFIX="dartdoc"
          if [ $GITHUB_EVENT_NAME == "pull_request" ]; then
            echo "Running sync for Pull Request Number: $PULL_REQUEST_NUMBER ..."
            REMOTE_PATH="pull/$PULL_REQUEST_NUMBER/$REMOTE_PATH_SUFFIX"
          else
            echo "Running sync for main branch (assumed given the triggers configured for this workflow) ..."
            REMOTE_PATH="main/$REMOTE_PATH_SUFFIX"
          fi
          aws s3 sync --acl public-read doc/api "s3://sdk.ably.com/builds/ably/ably-flutter/$REMOTE_PATH"

      - name: Set Deployment Status to Success
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: ${{ steps.define_deployment_constants.outputs.environment }}
          environment_url: ${{ steps.define_deployment_constants.outputs.environment_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: success
          mediaType: '{"previews": ["ant-man"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If the previous step (set deployment status to success) FAILS then this step will ALSO get run.
      - name: Set Deployment Status to Failure
        if: ${{ failure() }}
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/:repository/deployments/:deployment/statuses
          repository: ${{ github.repository }}
          deployment: ${{ fromJson(steps.create_deployment.outputs.data).id }}
          environment: ${{ steps.define_deployment_constants.outputs.environment }}
          environment_url: ${{ steps.define_deployment_constants.outputs.environment_url }}
          log_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          state: failure
          mediaType: '{"previews": ["ant-man"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
