on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.x'
          cache: true

      - name: Build Documentation
        run: |
          dart doc
          ls -al doc/api

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.ABLY_AWS_ACCOUNT_ID_SDK }}:role/ably-sdk-builds-ably-flutter
          role-session-name: "${{ github.run_id }}-${{ github.run_number }}"

      - name: Upload Documentation
        uses: ably/sdk-upload-action@v1
        with:
          sourcePath: doc/api
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dartdoc
