on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      
      - name: Get Flutter Packages
        run: flutter pub get

      - name: Install dartdoc global package via pub tool in the Flutter context
        run: |
          flutter pub global activate dartdoc

      - name: Build Documentation
        run: |
          env | grep FLUTTER_
          dartdoc
          ls -al doc/api
