on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      
      - name: Get Flutter Packages
        run: flutter pub get

      - name: Install dartdoc global package via pub tool in the Flutter context
        run: |
          flutter pub global activate dartdoc

      - name: Build Documentation
        run: |
          flutter pub global run dartdoc
          ls -al doc/api

      # Default shell is bash: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
      # jq emits `null` if the `pull_request` key is not found.
      - name: Experiment
        run: |
          PULL_REQUEST_NUMBER=`cat pull-request-event.json | jq .pull_request.number`
          if [ $PULL_REQUEST_NUMBER == "null" ]; then
            echo "Running for a branch, assumed to be main given the triggers configured for this workflow"
          else
            echo "Running for Pull Request Number: $PULL_REQUEST_NUMBER"
          fi
