on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Get Flutter Packages
        run: flutter pub get

      - name: Install dartdoc global package via pub tool in the Flutter context
        run: flutter pub global activate dartdoc

      - name: Use Intro Blurb
        run: |
          mv README.md README.md.bak
          mv API_REF_INTRO_BLURB.md README.md

      - name: Build Documentation
        run: |
          flutter pub global run dartdoc
          ls -al doc/api

      - uses: ably/sdk-upload-action@v1
        with:
          s3AccessKeyId: ${{ secrets.SDK_S3_ACCESS_KEY_ID }}
          s3AccessKey: ${{ secrets.SDK_S3_ACCESS_KEY }}
          sourcePath: doc/api
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          artifactName: dartdoc

      - name: Restore Readme
        run: |
          mv README.md API_REF_INTRO_BLURB.md
          mv README.md.bak README.md
